name: latest

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/latest.yml
      - cmd/**
      - internal/**
      - .golangci.yml
      - go.mod
      - go.sum
  push:
    branches: [main]
    paths:
      - .github/workflows/latest.yml
      - cmd/**
      - internal/**
      - .golangci.yml
      - go.mod
      - go.sum

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.34
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15"
          CGO_ENABLED: 1
      - run: go test -race ./...
