name: latest

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/pr.yml
      - cmd/**
      - internal/**
      - .dockerignore
      - .golangci.yml
      - Dockerfile
      - go.mod
      - go.sum

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v3
      - run: |
          docker buildx build \
            --progress plain \
            --target test \
            .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v3
      - run: |
          docker buildx build \
            --progress plain \
            --target lint \
            .

  docker:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build .
